apiVersion: apps/v1
kind: Deployment
metadata:
  name: baizura-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-baizura
  template:
    metadata:
      labels:
        app: my-baizura
    spec:
      containers:
      - name: my-container
        image: baizuradocker/intel5:latest
        ports:
        - containerPort: 8080
