name: cicd3
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the maven repository
        uses: actions/checkout@v4.1.5
      - name: list files
        run: ls -l
      - name: installing java 11 on the runner machine
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: verify java
        run: java -version
      - name: build to be done
        run: |
          mvn package
          ls -l
          ls -l ./target
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: docker image build
        run: |
          docker build -t myimage:${{ GITHUB.RUN_NUMBER }} .
          docker images
      - name: Docker container creation test
        run: |
          docker run -dt --name c1 myimage:${{ GITHUB.RUN_NUMBER }}
          docker ps
      - name: Login to Dockher Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker push
        run: |
          docker tag myimage:${{ GITHUB.RUN_NUMBER }} baizuradocker/intel5:${{ GITHUB.RUN_NUMBER }}
          docker tag myimage:${{ GITHUB.RUN_NUMBER }} baizuradocker/intel5:latest
          docker push baizuradocker/intel5:latest
          docker push baizuradocker/intel5:${{ GITHUB.RUN_NUMBER }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker container creation test
        run: |
          docker run -dt --name web1 baizuradocker/intel5:latest
          docker ps
          
